### ISSUE TITLE
AltStore said "Cannot activate 3 apps" but I just deleted an app to install another app. (Called "Cowabunga")

### ISSUE THREAD

**Issue by TotallyNotPooh** [altstoreio/AltStore#1123]
![altstorebug](https://user-images.githubusercontent.com/123549284/215276438-6db1c94c-46bc-4075-a6ba-ede64b261150.png)

**Comment by shanegillio** [comment]
Hi there! Have you already updated to AltStore 1.6?

**Comment by TotallyNotPooh** [comment]
Can't even update it bruh

**Comment by shanegillio** [comment]
Have you sideloaded any apps directly with AltServer? If you have any app information that is not tied to AltStore itself, it may be running into issues there. You can try checking the AppIDs list for anything that maybe is registered but not appearing on the My Apps page

**Comment by TotallyNotPooh** [comment]
Nah thanks just updated complete lol
