### ISSUE TITLE
AltStore for M1 Mac

### ISSUE THREAD

**Issue by JackSalzman** [altstoreio/AltStore#1131]
It would be awesome if you could install altstore on an M1 Mac to side load iOS apps to the Mac.

**Comment by dramikei** [comment]
[PlayCover](https://playcover.io) already exists for that no?
side loading apps to Mac is probably very is not entirely different than side loading on iOS so its very unlikely that this will be picked up.

**Comment by shanegillio** [comment]
Hi there! Thank you for the request, and I just want to note that we have marked this as a feature request item on another issue already. I'm going to lose this as a duplicate, but know that we have seen your request.
