### ISSUE TITLE
Cannot use AltServer because Mail plugin doesn't work

### ISSUE THREAD

**Issue by jadenquinn** [altstoreio/AltStore#1132]
I'm trying to use AltServer for my iPad 2, but when I try to install AltStore onto it, it doesn't work, citing an issue with the Mail plugin.

**Comment by ChuanqingYang** [comment]
> Hello! As far as we know, we have updated AltServer to run on MacOS. Can you detail what is happening that is causing the mail plugin not to work?

When I click install mail-plugin with mail app running,there is nothing happened and in mail-plugin tab I can not find the plugin which should be there

**Comment by TimeZlicer** [comment]
@shanegillio 

Good day

I am on M2 MBA, macOS Ventura 13.2.1

I am facing similar issue 'Install Mail Plug-in' has not effect, i.e. no plug-in appears in mail-settings

Please let me know if there is anything I can try or provide more information, thanks!

**Comment by shanegillio** [comment]
The mail plug-in seems to be working, so I would maybe try uninstalling AltServer completely and reinstalling? Have you ever modified anything in the past with regards to the mail plug-in?

**Comment by TimeZlicer** [comment]
Thank you! It works
