### ISSUE TITLE
The 3-App Limit in AltStore is no longer necessary.

### ISSUE THREAD

**Issue by orangesummertime** [altstoreio/AltStore#1133]
See this: https://github.com/zhuowei/WDBRemoveThreeAppLimit/issues
Using this the limit of signed apps' amount in iOS 14 - 15.7.1 and iOS 16.0 - 16.1.2 could be removed now. Therefore, it's no longer necessary to set a limit in AltStore.

**Comment by lingsoul** [comment]
Looking forward to the new version will remove the restrictions as soon as possible
![IMG_8329](https://user-images.githubusercontent.com/22099083/217192759-de5430dd-0ae9-452b-82ca-c76f487773a7.jpg)

**Comment by wg481** [comment]
Unfortunately the bug that makes zhuowei's system work has been patched.

**Comment by lingsoul** [comment]
> Unfortunately the bug that makes zhuowei's system work has been patched.

I just tried it and it is still available （iPhone13pro  ios15.7）

**Comment by zanjie1999** [comment]
https://wwkh.lanzout.com/iRV6Q0njje7i
use this "SideStore UltraNightly UnlimitedApps"
and use "WDBRemoveThreeAppLimit-v1.0"
all wii OK and without AD

**Comment by omegion3** [comment]
now it's still necessary for iOS 16.2 and aboove
