### ISSUE TITLE
AltServer.ServerError 2008

### ISSUE THREAD

**Issue by mikperk** [altstoreio/AltStore#1144]
I can't install apps via the latest AltStore BETA or non-beta version anymore.

Instead I get this message:

`Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/771204CC-A543-4456-B9DB-02F580980CFC/App.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/771204CC-A543-4456-B9DB-02F580980CFC/App.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/771204CC-A543-4456-B9DB-02F580980CFC/App.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory`

Device: iPhone Pro Max 13, iOS 16.3.1

EDIT: Today it worked fine.

**Comment by LucasIsGood** [comment]
how did u make it works , i have the same issue.

**Comment by mikperk** [comment]
> 

I have done nothing. The next day, for some inexplicable reason, it worked again.

**Comment by dean-github** [comment]
It happens to me months ago when I updated the newer releases and always got the same issue with altserver. It left me running with the old version of 17.3x, still working for now. But I hope it work again one day with newer versions.

**Comment by LucasIsGood** [comment]
@dean-github I solved this problem by deleting the old version of the applications installed by Altstore. I guess u face the same problem.

**Comment by dean-github** [comment]
You’re right. I always tried to overwrite it with newer versions to keep exiting data. It works. Thank you very much. Sent from a phoneOn 19 Apr 2023, at 15:07, LucasIsGood ***@***.***> wrote:﻿
@dean-github I solved this problem by deleting the old version of the applications installed by Altstore. I guess u face the same problem.

**Comment by LucasIsGood** [comment]
:)  @dean-github

**Comment by alexchandel** [comment]
Need a permanent fix for this for updating apps.  AltStore shouldn't throw an error just for installing an updated app.

**Comment by Gangsyl** [comment]
> Need a permanent fix for this for updating apps.  AltStore shouldn't throw an error just for installing an updated app.

I have the same problem
