### ISSUE TITLE
Unable to refresh store A core Data error occurred

### ISSUE THREAD

**Issue by KeyFlyz** [altstoreio/AltStore#1151]
![image](https://user-images.githubusercontent.com/35471760/220054576-f672f973-baf0-475e-a29e-c02c86686d39.jpeg)

![image](https://user-images.githubusercontent.com/35471760/220054612-e827535c-15d7-4b15-b1c3-5c57c258ba5f.jpeg)

Just started happening a day ago.

**Comment by KeyFlyz** [comment]
IOS 16.3 iPhone XS Max

**Comment by shanegillio** [comment]
We released info today on this - https://twitter.com/altstoreio/status/1627807467584253952?s=20
