### ISSUE TITLE
MailPlugin does not appear in Mail extensions

### ISSUE THREAD

**Issue by johansmolinski** [altstoreio/AltStore#1169]
Trying to set up AltServer for the first time. I get to the point where I have installed the MailPlugin from the AltServer toolbar icon. Then I open the Mail app and view Mail->Settings->Extensions. Nothing is there. In the AltServer menu, the Install MailPlugin has changed to Uninstall MailPlugin, so obviously AltServer believes it is installed while the Mail app is of another opinion.

MacBook Pro 16" M1 Max
macOS  Ventura 13.2.1
Mail 16.0
AltServer 1.6

**Comment by purplespider** [comment]
Just came here with the same problem! Thanks for leaving the solution.
