### ISSUE TITLE
NEW ERROR: There is no provisioning profile with the requested identifier on this team.

### ISSUE THREAD

**Issue by Bartoliinii** [altstoreio/AltStore#1177]
There is a new error that I have encountered just today. It says:

There is no provisioning profile with the requested identifier on this team.

Have you guys encountered it? How to solve it?

**Comment by cjburkey01** [comment]
You beat me to it: https://github.com/altstoreio/AltStore/issues/1178

**Comment by superfreeman1989** [comment]
Same here.

**Comment by justinokay** [comment]
Me too.

**Comment by PurpleWolfyy** [comment]
Also encountering this same issue. there seems to be no fix atm.

**Comment by Starcraft426** [comment]
i have the problem too with ios 12.5.7 on iphone 6

**Comment by ItzGolbe** [comment]
same here. iPad 10 iPadOS 16.3.1, AltStore 1.6.1

**Comment by JayMiki** [comment]
same here

**Comment by yukiime** [comment]
this is due to a server-side change by Apple

**Comment by kunalvaghelakunal** [comment]
Got the same issue with the Latest IOS + Latest Alt Server


![WhatsApp Image 2023-03-21 at 9 49 11 AM](https://user-images.githubusercontent.com/20610760/226626376-5ca1a457-5d6a-4f3f-8145-47b5ee8af616.jpeg)

**Comment by ptntp** [comment]
same here. iPhone 13 ProMax & iOS 16.4, AltStore 1.6rc (71)

**Comment by Sanaan01** [comment]
Yep same

**Comment by brunoaduarte** [comment]
Same issue here +1

**Comment by Enzodtz** [comment]
Same, unfortunately. Read on reddit that they're working on this.

**Comment by cjburkey01** [comment]
I think you may want to close this issue as they addressed this on Twitter (https://twitter.com/altstoreio/status/1638237156777816071?s=46&t=93Po4dmjeEdGzNWLkduNAg) and it will be available for free users soon

**Comment by dumbelldoor** [comment]
Same with me, waiting for a fix!

**Comment by showmak** [comment]
Same issue here

**Comment by 28tad** [comment]
I installed a new version and it solved my problem
https://kemono.party/patreon/user/14154737/post/80344882

**Comment by skver0** [comment]
my man dropped the patreon leak website like its nothing

**Comment by veselcraft** [comment]
same, ios 16.0 and latest altserver

**Comment by mitchcecg** [comment]
following

**Comment by SJodi** [comment]
Same here.

**Comment by JohnDarc95** [comment]
Same Here
iOS: 16.3.1
Alt Server: 1.6.1.0

**Comment by WoodpeckerBaby** [comment]
![image](https://user-images.githubusercontent.com/14303318/226957955-1443a4c6-073e-4ae9-8396-c9d9a9ad0d13.png)

**Comment by solomwn** [comment]
yes "AltServer could not be found" is the new error come up

**Comment by joeriandreas** [comment]
There is a fix in the beta version

**Comment by sohel2020** [comment]
> There is a fix in the beta version

can you send me the link here ?

**Comment by Frei14** [comment]
> > There is a fix in the beta version
> 
> 
> 
> can you send me the link here ?
> 
> 
> 
> 

https://twitter.com/altstoreio/status/1638599316762664974?s=46&t=UsFWkPJywIRB-1LoLcz0vw

**Comment by joeriandreas** [comment]
DO NOT delete your sideloaded apps or else you will lose your save data. 

Once the fix is released, you will be able to refresh your apps — even if they are expired — and your save data will still be there.

**Comment by cjburkey01** [comment]
I recommend closing this now, the fix is public: https://twitter.com/altstoreio/status/1638599316762664974?s=46&t=93Po4dmjeEdGzNWLkduNAg

**Comment by RII798** [comment]
I had the same error. I updated AltServer on PC and reinstalled AltStore on iPhone and it worked (Windows 10, AltServer 1.6.1.0, iPhone XR, iOS 16.3.1)

**Comment by xuanthanhtsd** [comment]
I follow the instruction and it worked: Update the AltServer in My computer (MacOS). Plug the cable and reinstall manually AltStore to My Phone. Reinstall the uYouPlus

**Comment by Bartoliinii** [comment]
Since the new update of Altstore, everything should be fine. I'm closing this issue.

**Comment by Game-Warrior** [comment]
I am having this same error. Using Emacs 29 has not solved it for me. I tried Emacs -Q and it was able to to open my files just fine. 

generated  Nov 03, 2023 18:50:34
system     MacOS 14.1 Darwin 23.1.0 arm64
emacs      29.1 ~/.emacs.d/
doom       3.0.0-pre PROFILE=_@0 HEAD -> master 98639850 2023-10-07 02:33:45
	   +0200 ~/.config/doom/
shell      /bin/zsh
features   ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3
	   THREADS TOOLKIT_SCROLL_BARS TREE_SITTER XIM ZLIB
traits     batch server-running envvar-file custom-file
modules    :config use-package :completion company vertico :ui doom
	   doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs
	   (vc-gutter +pretty) vi-tilde-fringe workspaces zen :editor (evil
	   +everywhere) file-templates fold snippets word-wrap :emacs (dired
	   +icons) electric (ibuffer +icons) undo vc :term term vterm :checkers
	   syntax grammar :tools biblio editorconfig (eval +overlay) lookup lsp
	   magit pdf tree-sitter :os macos :lang (cc +lsp) emacs-lisp (go +lsp)
	   javascript (kotlin +lsp) (lua +lsp) markdown nix (org +gnuplot
	   +pretty +pandoc +noter +dragndrop +journal +present +publish) (python
	   +lsp) sh web yaml :email (mu4e +org +gmail +evil) :app calendar
	   everywhere rss :config literate (default +bindings +smartparens)
packages   (evil-tutor) (tldr) (org-tree-slide) (org-auto-tangle)
	   (org-re-reveal) (ox-twbs) (dired-open) (dired-subtree) (peep-dired)
	   (emojify) (beacon) (rainbow-mode) (resize-window) (fountain-mode)
	   (wc-mode) (ivy-posframe) (yasnippet) (palimpsest) (emmet-mode)
	   (elfeed-goodies) (mw-thesaurus) (writeroom-mode) (olivetti) (org-ref)
	   (mastodon) (ox-pandoc) (pandoc) (request) (2048-game) (poetry)
	   (pretty-symbols) (magit-todos) (org-anki) (anki-connect) (ox-gfm)
	   (ivy-bibtex) (anki-mode) (go-translate) (transient :pin
	   c2bdf7e12c530eb85476d3aef317eb2941ab9440 :recipe (:host github :repo
	   magit/transient)) (with-editor :pin
	   bbc60f68ac190f02da8a100b6fb67cf1c27c53ab :recipe (:host github :repo
	   magit/with-editor)) (blamer) (org-noter) (nov.el) (ox-epub) (esxml)
	   (burly) (eshell-prompt-extras) (chatgpt-shell) (dall-e-shell)
	   (ob-chatgpt-shell) (synosaurus) (academic-phrases) (pacmacs)
	   (fireplace) (jinx) (org-bullets) (fedi) (lem) (org-cliplink) (ellama)
	   (org-timeblock) (llm)
