### ISSUE TITLE
Experiencing Error #3017 When Refreshing Apps

### ISSUE THREAD

**Issue by cjburkey01** [altstoreio/AltStore#1178]
### Versions:
- iPhone 11 Pro running iOS 15.5
- AltStore 1.6.1 installed from AltServer 1.6

### Summary
When attempting to refresh or install apps from a repository/IPA from my phone, I receive the following error: `There is no provisioning profile with the requested identifier on this team`. I noticed on the error codes page, there is [an entry for this error](https://faq.altstore.io/getting-started/error-codes#3017-there-is-no-provisioning-profile-with-the-requested-identifier-on-this-team.), but it's just a placeholder. Refreshing the AltStore from AltStore itself on the phone also fails with the same error.

### What I've Tried
I have tried reinstalling AltStore from AltServer and this performs successfully both if the store is already on the phone and if it has been deleted. Even after doing so, however, the issue persists.

**Comment by wa1id** [comment]
Same issue, running iOS 16.3.1

**Comment by Thyssenkrupp234** [comment]
Same error here, just started experiencing it right now on iPhone 8 iOS 16.1.

**Comment by cleavenworth** [comment]
Same here, 14 Pro Max on 16.2. Just reinstalled fresh and still seeing this error.

**Comment by criccadamus** [comment]
Same here, 13 Pro on iOS 16.3.1. Tested an install of the same .ipa file i've tried in macOS with no issue.

**Comment by onlybrezel** [comment]
Same here

**Comment by Thyssenkrupp234** [comment]
@criccadamus I got the same error on mac sideloadly, weird how you had no issue.

**Comment by mariovaoj** [comment]
Same problem here. It only appears when refreshing or installing apps on phone. There's no problem installing altstore from altserver, just in the iOS app itself.

**Comment by passsssssssss** [comment]
Same happening to me. Is it on Apple's end?

**Comment by superfreeman1989** [comment]
Same thing here. Just happening today it seems.

**Comment by GodlikePenguin** [comment]
Looks like they posted an update on Twitter. Server side change from Apple that will require a change to Altstore.

https://twitter.com/altstoreio/status/1637953768728801282

**Comment by benbaptist** [comment]
I just refreshed AltStore from being expired on my iPad Mini, and while AltStore installed just fine from AltServer directly, none of my apps will refresh. Thank goodness it's not just me though; I was driving myself crazy trying to figure it out until I finally found these issues. (googling the error gives me nothing!)

**Comment by jljeee** [comment]
Same here, Iphone se gen1 , iphone 7p and ipad pro 2022.AltStore reintalled from PC successed but it cann't refresh others.

**Comment by schweppes-0x** [comment]
Same problem here, Iphone 13pro, iOS 16.3, AltStore (latest).

**Comment by abelparayil** [comment]
I have the same issue. Is there a timeline on when it could be fixed?

**Comment by oomek** [comment]
Can we have a status update please? I lost Youtube after trying to reinstall it.

**Comment by JaeMyeongSon** [comment]
I have the same problem

**Comment by JefferyT51** [comment]
Sharing my comment from issue #1177  (Having the same problem on my 13 Pro).  It looks like the team has noted the issue on their Twitter and Mastodon accounts and a fix is going to be released "soon".

https://twitter.com/altstoreio/status/1637953768728801282

https://fosstodon.org/@altstore/110058165833838798

**Comment by brunoaduarte** [comment]
Same issue here +1

```
Install ....... Failed
AltStore.AppleDeveloperError 3017
There is no provisioning profile with the requested identifier on this team.
```

**Comment by oomek** [comment]
An fix for app breaking error only for patrons?
You've got to be joking.
https://www.patreon.com/posts/80344882

**Comment by cjburkey01** [comment]
> A fix for app breaking error only for patrons?
> 
> You've got to be joking.
> 
> https://www.patreon.com/posts/80344882

I guess it makes sense with their beta model, but given the nature of this issue I hope they'll push this version through relatively quickly.

**Comment by oomek** [comment]
Hiding extra features behind a paywall is one thing, but demanding money for core functionality out of a sudden that's a low blow.

**Comment by cjburkey01** [comment]
I won't defend it and I agree with what you said, it should just be a patch release but I guess we have to be patient to see what they end up doing. [In their tweet](https://twitter.com/altstoreio/status/1638237275577282586?s=46&t=93Po4dmjeEdGzNWLkduNAg) they said it'll be available for everyone else "shortly." Who knows how long it'll be 🤷

**Comment by Spygamer10** [comment]
> Hiding extra features behind a paywall is one thing, but demanding money for core functionality out of a sudden that's a low blow.

It ain’t cool, they have the fix but want to hold it until they make money, running a free service can be hard but the app is not functioning

**Comment by passsssssssss** [comment]
I think that they don’t know yet if the fix is 100% effective and, instead of releasing an half assed update, they’re waiting to test it. So, as part of their beta/to be tested features, they released it for Patrons.
Inevitably some choices are taken instead for others for profit reasons, they could’ve released it as a beta fix publicly, but we can’t argue when a services is offered for free.

**Comment by oomek** [comment]
Half assed update is always better than dead app.

**Comment by Enzodtz** [comment]
> I think that they don’t know yet if the fix is 100% effective and, instead of releasing an half assed update, they’re waiting to test it. So, as part of their beta/to be tested features philosophy, they released it for Patrons. Inevitably some choices are taken instead for others for profit reasons, they could’ve released it as a beta fix publicly, but we can’t argue when a services is offered for free.

🎯. This should be basical software development knowledge

**Comment by CLOUDUH** [comment]
https://twitter.com/altstoreio/status/1638237156777816071

**Comment by cjburkey01** [comment]
I think I should close this now, it should be fixed shortly :)

**Comment by D1reW0lf** [comment]
> Looks like they posted an update on Twitter. Server side change from Apple that will require a change to Altstore.
> 
> https://twitter.com/altstoreio/status/1637953768728801282

Thank you for letting us know.

**Comment by cjburkey01** [comment]
For reference: https://twitter.com/altstoreio/status/1638599316762664974?s=46&t=93Po4dmjeEdGzNWLkduNAg
