### ISSUE TITLE
couldn't find altserver icon on win11's taskbar

### ISSUE THREAD

**Issue by dfdfwff** [altstoreio/AltStore#1184]
I've used altserver on my windows11 over one month, but yesterday i found its icon missing on taskbar.
I've tried to uninstal and reinstall but it doesn't work

**Comment by POTEHE** [comment]
same on windows10

**Comment by Roroca-1** [comment]
same issue with win10 pro

**Comment by shanegillio** [comment]
this should have been solved, so let me know if it's still an issue
