### ISSUE TITLE
Can't install AltStore

### ISSUE THREAD

**Issue by bzuruce** [altstoreio/AltStore#1197]
<img width="920" alt="Screenshot 2023-04-20 at 7 11 41 AM" src="https://user-images.githubusercontent.com/63930549/233393965-40da00d0-811c-4c2e-8ce2-3691e68dcd3e.png">

After installing AltStore once successfully, a few days later, all my installed apps and AltStore itself prompts an error message upon launching: "AltStore" is no longer available. Trying to install from the AltServer, it fails. I used the main Apple ID from the old install and a new one. I am running iOS 16.4.1 (before and after) and macOS 13.2.1(before and after)

**Comment by UnknownSkeletalRemains** [comment]
same here

**Comment by bzuruce** [comment]
@UnknownSkeletalRemains I fixed this by turning on App Store in Screen Time.
