### ISSUE TITLE
ERROR CODE 2013 (The provided anisette data is invalid)

### ISSUE THREAD

**Issue by lts20050703** [altstoreio/AltStore#1202]
The provided anisette data is invalid.

Please download the latest versions of iTunes and iCloud directly from Apple, and not from the Microsoft Store.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87189679/236684341-b2fbacff-ee2c-4f3c-97b0-b53bfd89121e.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87189679/236381364-04bd69ea-a48d-4499-834a-e18f9d463de9.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87189679/236381502-c19ea58a-cb1b-4594-823c-1cd573343fc4.jpeg">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87189679/236684258-50e6a6a5-8e69-4622-b10f-97696ad30056.png">

**Comment by shanegillio** [comment]
Yes, you will need to download iTunes and iCloud directly from Apple. You can find those links here - https://faq.altstore.io/getting-started/how-to-install-altstore-windows
