### ISSUE TITLE
AltPlugin incompatible with Mail 16.0

### ISSUE THREAD

**Issue by Fox2518** [altstoreio/AltStore#1213]
Hi,
I have a problem since today.
Mail disables the plugin because it says it is not compatible with mail 16.0

Regards,

**Comment by shanegillio** [comment]
Have you ever modified the mail plug-in folders? Otherwise, you should just need to click update plugin on AltServer.

**Comment by spider623** [comment]
There is no plugin option anymore

<img width="773" alt="image" src="https://github.com/altstoreio/AltStore/assets/6705601/0ee8464a-428f-473c-8d20-fa7c71f6a0eb">

**Comment by swaggio7** [comment]
Happens to me as well

**Comment by T-SLA** [comment]
Is there a solution to this? I am trying to install altstore for the first time and there is no "Manage Plug-ins" button.  I am on MacOS Sonoma 14.0, Mail 16.

**Comment by pejeio** [comment]
Has a solution been found for this issue?

**Comment by T-SLA** [comment]
There is no solution.  It seems impossible to get AltStore on an iPad now. :-(

**Comment by shanegillio** [comment]
The newest AltServer update removes the need for mail plug-ins
