### ISSUE TITLE
Altstore ipa

### ISSUE THREAD

**Issue by Yeudhhdhdv** [altstoreio/AltStore#1214]
Hey my version iOS 12.5.5 jailbroken Whit unc0ver

Is it possible to download Altstore whithout computer ?

i want to download Altstore .ipa i want is it possible ?

I download ipa file Whit filza

Thank for Help me

**Comment by BAS27-BKK** [comment]
> Hey my version iOS 12.5.5 jailbroken Whit unc0ver
> 
> Is it possible to download Altstore whithout computer ?
> 
> i want to download Altstore .ipa i want is it possible ?
> 
> I download ipa file Whit filza
> 
> Thank for Help me
