### ISSUE TITLE
altstore mail plugin macOS Sonoma

### ISSUE THREAD

**Issue by hcarrega** [altstoreio/AltStore#1223]
maybe they change mail plugins, cant find it now

**Comment by peruginiandrea** [comment]
I tried all the workarounds I could think of, but it seems impossible now :( hopefully there will be another way that doesn’t require using mail plugins

**Comment by peruginiandrea** [comment]
Update: I’ve just seen this 

https://twitter.com/altstoreio/status/1666173037732044801?s=20

**Comment by Supermas18** [comment]
I am having the same issue too. The manage mail plug-ins button has gone missing. If anyone finds a fix please share

**Comment by roeegh** [comment]
> https://twitter.com/altstoreio/status/1666173037732044801?s=20

Disabling SIP and setting the correct boot args seems to allow Altstore to work. The `Manage Plug-ins` button still doesn't appear in the Mail preferences but installing and refreshing seems to work

**Comment by ovisirius** [comment]
Legacy plug-ins have been disabled in Sonoma. There's no way around this besides disabling SIP.
Probably next solution will be to ditch Mail plugin altogether.
https://twitter.com/i/web/status/1669046033941159938

**Comment by shanegillio** [comment]
Closing this issue as a duplicate - this has been reported a few times already
