### ISSUE TITLE
iPadOS UI

### ISSUE THREAD

**Issue by bukaixyz** [altstoreio/AltStore#1226]
I suggest AltStore support iPadOS UI.

![image](https://github.com/altstoreio/AltStore/assets/85857425/1cf2970d-33a3-40da-8c43-af22db1ce9b9)

Altstore can't full screen on iPad.🌝

**Comment by bukaixyz** [comment]
@rileytestut

**Comment by shanegillio** [comment]
Hi! We do know of this issue and have other requests. I'm just closing this as a duplicate, but know that we have it in mind.
