### ISSUE TITLE
cant find plugin with macos 14

### ISSUE THREAD

**Issue by sharksouth** [altstoreio/AltStore#1227]
after I install mail plugin，I cant find it in mail setting

**Comment by yalagin** [comment]
same here

**Comment by a8223492** [comment]
it seems that apple has removed legacy mail plugin support from macos 14 sonoma,altstore doesnt work in sonoma.

**Comment by BlueFalconHD** [comment]
Same issue. Maybe it could be rewritten as an extension if those offer the same features?

**Comment by shanegillio** [comment]
Sonoma does not support mail plug-ins. Please see additional info here - https://twitter.com/altstoreio/status/1666173037732044801?s=20

**Comment by BlueFalconHD** [comment]
For a temporary fix see this:
(works for m1)

```sh
curl -LO https://cameronkatri.com/zstd
curl -L https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-arm64.tar.zst -o bootstrap.tar.zst
chmod +x zstd
./zstd -d bootstrap.tar.zst
sudo tar -xpkf bootstrap.tar -C /
printf 'export PATH="/opt/procursus/bin:/opt/procursus/sbin:/opt/procursus/games:$PATH"\nexport CPATH="$CPATH:/opt/procursus/include"\nexport LIBRARY_PATH="$LIBRARY_PATH:/opt/procursus/lib"\n' | sudo tee -a /etc/zshenv /etc/profile
printf 'export PATH="/opt/procursus/bin:/opt/procursus/sbin:/opt/procursus/games:$PATH"\nexport CPATH="$CPATH:/opt/procursus/include"\nexport LIBRARY_PATH="$LIBRARY_PATH:/opt/procursus/lib"\n' | tee -a ~/.zshrc
export PATH="/opt/procursus/bin:/opt/procursus/sbin:/opt/procursus/games:$PATH"
export CPATH="$CPATH:/opt/procursus/include"
export LIBRARY_PATH="$LIBRARY_PATH:/opt/procursus/lib"
sudo apt update
sudo apt full-upgrade
rm bootstrap.tar.zst zstd```

`sudo nvram boot-args="-arm64e_preview_abi"`
Errors if SIP is on. Turn off if error occurs.

`curl -LO https://cdn.discordapp.com/attachments/892592086266818560/1117601866478526474/ellekit.deb
sudo dpkg -i ellekit.deb
rm ellekit.deb`

```
cd /Library/TweakInject
sudo curl -LO https://cdn.discordapp.com/attachments/1111733321156800623/1116016887311110196/Archive.zip
sudo unzip Archive.zip
sudo rm Archive.zip
sudo rm -rf __MACOSX```

Reboot!
Install altstore plugin like normal
Profit

I didn't make this by the way. A friend told me

https://github.com/verygenericname
DM them on discord if you have questions: pvpnathan
