### ISSUE TITLE
Altstore is not avalieble and dev profile is deleted automatically

### ISSUE THREAD

**Issue by paulb2299** [altstoreio/AltStore#1232]
Hello, I'm facing issues with Altstore recently: I reinstall the app, can open it once, but doesn't reload my app (uYouPlus), so I close the app, try to open it again and "Altstore is not avaliable" message appears. Also, my dev profile suddenly is deleted in settings. What's going on? I tried reinstalling the app several times but always get the same message. It started yesterday, before that, was woking fine.

**Comment by supercam19** [comment]
Here is how I fixed this problem: Re-install Altstore from your computer, and once it's done installing, do NOT open it. On your phone, go into Settings>General>VPN and Device Management and trust your apple ID. Now you should be able to open Altstore and refresh/install apps.

**Comment by paulb2299** [comment]
> Here is how I fixed this problem: Re-install Altstore from your computer, and once it's done installing, do NOT open it. On your phone, go into Settings>General>VPN and Device Management and trust your apple ID. Now you should be able to open Altstore and refresh/install apps.

Thank you!
