### ISSUE TITLE
Mail Plugin removed in macOS 14.0 developer beta

### ISSUE THREAD

**Issue by Charlie102308** [altstoreio/AltStore#1234]
<img width="752" alt="Screenshot 2023-06-23 at 6 26 43 PM" src="https://github.com/altstoreio/AltStore/assets/94617775/0d501b12-c547-4ff1-b9b8-320d1ac88dfe">
As seen in the screenshot, Apple removed the mail Plug-in in the mail app.Can not refresh app anymore

**Comment by dzxt** [comment]
how it was solved?

**Comment by Charlie102308** [comment]
1.enter recovery mode by pressing cmd + R
2.open terminal and type csrutil disable
3.type nvram boot-args="amfi_get_out_of_my_way=0*1"
4.reboot
This is the only way as I know to get it working from the official twitter account
