### ISSUE TITLE
Altstore was unable to use an existing signing certificate Refresh Now/Refresh Later

### ISSUE THREAD

**Issue by han9over** [altstoreio/AltStore#1242]
This issue started happening recently. I have 3 devices and I'm using same apple ID on all of them. This setup worked fine for last year or so, Not sure if something changed on apple side. Using altserver on Windows. I deleted Altstore and apps on all devices. I reinstalled on one device and refresh the altstore before I reinstall other apps. Then I installed altstore on second device and refresh it and then the apps were installed. Now, when I go to first device and do refresh of altstore, it throws this popup in AltStore and unless I do refresh now which basically reinstall all my apps, I can't refresh.

**Comment by jljeee** [comment]
I met this problem. I had a ipad pro 2022 with ios16.6.1, iphone 7p with ios 15.7.9, iphone 7 with ios 15.7.8.
I brought a new iphone 14P ios 16.4.1 last week and move data from iphone 7p, and I move iphone 7 data to 7P, then I install the altstore, this problem appear. using same ID in altstore.
Solove:
Refresh all in the iphone 7P, and make sure the app altstore can refresh normally (not reinstall), log out others devices ID in the altstore, then log in, this time will show a 1234 screen and show "altstore unable..." , choose "refresh now", wait for finishing. 
All should be normal.

**Comment by jljeee** [comment]
I met this problem. I had a ipad pro 2022 with ios16.6.1, iphone 7p with ios 15.7.9, iphone 7 with ios 15.7.8.
I brought a new iphone 14P ios 16.4.1 last week and move data from iphone 7p, and I move iphone 7 data to 7P, then I install the altstore, this problem appear. using same ID in altstore.
Solove:
Refresh all in the iphone 7P, and make sure the app altstore can refresh normally (not reinstall), log out others devices ID in the altstore, then log in, this time will show a 1234 screen and show "altstore unable..." , choose "refresh now", wait for finishing. 
All should be normal.

**Comment by jljeee** [comment]
I met this problem. I had a ipad pro 2022 with ios16.6.1, iphone 7p with ios 15.7.9, iphone 7 with ios 15.7.8.
I brought a new iphone 14P ios 16.4.1 last week and move data from iphone 7p, and I move iphone 7 data to 7P, then I install the altstore, this problem appear. using same ID in altstore.
Solove:
Refresh all in the iphone 7P, and make sure the app altstore can refresh normally (not reinstall), log out others devices ID in the altstore, then log in, this time will show a 1234 screen and show "altstore unable..." , choose "refresh now", wait for finishing. 
All should be normal.

**Comment by han9over** [comment]
> I met this problem. I had a ipad pro 2022 with ios16.6.1, iphone 7p with ios 15.7.9, iphone 7 with ios 15.7.8. I brought a new iphone 14P ios 16.4.1 last week and move data from iphone 7p, and I move iphone 7 data to 7P, then I install the altstore, this problem appear. using same ID in altstore. Solove: Refresh all in the iphone 7P, and make sure the app altstore can refresh normally (not reinstall), log out others devices ID in the altstore, then log in, this time will show a 1234 screen and show "altstore unable..." , choose "refresh now", wait for finishing. All should be normal.

I just moved on to sidestore. No more dealing with being at home. Now I can refresh anywhere with a wifi

**Comment by han9over** [comment]
Closing as I no longer need support.
