### ISSUE TITLE
I can't enable JIT.

### ISSUE THREAD

**Issue by pantendo** [altstoreio/AltStore#1248]
When I try enabling it, it says "JIT could not be enabled for _____".

Anyone know how to fix this? Do I need to use a third-party software?

**Comment by shanegillio** [comment]
https://app.gitbook.com/s/Afe8qEztjcTjsjjaMBY2/how-to-use-altstore/altjit

**Comment by shanegillio** [comment]
https://faq.altstore.io/how-to-use-altstore/altjit
