### ISSUE TITLE
After updating altstore cannot install or refresh sideloaded app

### ISSUE THREAD

**Issue by futurepr0n** [altstoreio/AltStore#1251]
Hi, as stated I’m having some issue where now after refresh I’m suddenly getting errors when trying to refresh or reinstall a previously installed app. 

![IMG_0346](https://github.com/altstoreio/AltStore/assets/478986/46cce660-8a33-4ee6-a7db-18dfccde8965)

I have tried tethered using USB, wifi and by trying to use the refresh as well as add new app with same ipa.

**Comment by sy-ph** [comment]
Yep, same issue, tried other Youtube clients + other IPA sideloading software, same problem every time.

**Comment by 7596ff** [comment]
same issue here, worked after i reinstalled the real youtube app.

**Comment by futurepr0n** [comment]
Ended up working after uninstalling and reinstalling everything
