### ISSUE TITLE
Having issues on the iOS 17 Public Beta

### ISSUE THREAD

**Issue by SpamixOfficial** [altstoreio/AltStore#1271]
Hello!

I'm having an issue with my enabling AltJIT on iOS 17 because the Developer Disk can't be found. I've made some research on the subject and it seems like they are moving from developer disks to something else for iOS 17. Do anyone have any idea on how I would enable AltJIT as I have no idea by the time I'm writing this.

Thanks for any help!
:D

**Comment by shanegillio** [comment]
you can follow #1228 for info
