### ISSUE TITLE
AltSign.Error 0

### ISSUE THREAD

**Issue by fandongtongxue** [altstoreio/AltStore#1284]
Error Description
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

Failure Reason
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

Title
Failed to Install Simple Live

Source File
ALTSigner.mm

Source Line
432

ipa is below
[ios_no_sign(1).ipa.zip](https://github.com/altstoreio/AltStore/files/12543444/ios_no_sign.1.ipa.zip)

**Comment by fandongtongxue** [comment]
转Sideloadly了

**Comment by EduardoAlezandro** [comment]
how you resolved this?
