### ISSUE TITLE
AltStore 1.7 crashes in jailbroken state

### ISSUE THREAD

**Issue by burkybang** [altstoreio/AltStore#1290]
I updated to AltStore 1.7 and AltServer 1.7, and now I'm unable to open AltStore while my iPhone is jailbroken. It only opens when I'm not jailbroken. It does not open while in safe mode.

**Comment by slowmotionary** [comment]
Same issue on iOS 14.8 iPhone 11 Pro Max. I got this error once when opening while unjailbroken
![3C0A6CE7-62E4-4076-B566-A5303B50465D](https://github.com/altstoreio/AltStore/assets/66421052/75b6887c-270e-4b30-b610-8d701a9309ed)

**Comment by konedaly** [comment]
me same too, Just downgrade to ver.1.6.3 is working

**Comment by burkybang** [comment]
I tried looking for how to downgrade before creating this issue, but I couldn’t find anything. Do you have instructions?

**Comment by ahmedmager** [comment]
How to downgrade to 1.6.3
1.7 not working

**Comment by IcyCarbide** [comment]
1.7 not working for me just crashes 
I hope this gets resolved soon I lose my jailbreak in 2 days

**Comment by IcyCarbide** [comment]
I managed to get v1.6.3 from here : https://f000.backblazeb2.com/file/altstore/apps/altstore/1_6_3.ipa

**Comment by burkybang** [comment]
Okay great. Normally I install the latest version via AltServer. How can I install the IPA?

**Comment by bradleytechman** [comment]
A fix is being worked on, should come out soon

**Comment by konedaly** [comment]
https://cdn.altstore.io/file/altstore/apps/altstore/1_6_3.ipa

**Comment by shanegillio** [comment]
Option to downgrade is now available: https://twitter.com/altstoreio/status/1704930963774460100
