### ISSUE TITLE
AltServer not updating and installing on 10.15 Catalina

### ISSUE THREAD

**Issue by kennethlinzj** [altstoreio/AltStore#1295]
I'm on macOS Catalina 10.15.7 and AltServer 1.6, and AltServer reports that it is on the latest version when i try to check for updates. Downloading the latest version (1.7) from the main website gives me an app that I can't open (it says it requires macOS 11 and newer, even though the website says it requires 10.14.4 or newer)
![Screenshot 2023-09-21 at 9 02 15 PM](https://github.com/altstoreio/AltStore/assets/32647180/ac129293-c0ba-465c-8a80-882b61b95491)
![Screenshot 2023-09-21 at 9 02 09 PM](https://github.com/altstoreio/AltStore/assets/32647180/96df8a5f-eb76-4a93-a0a6-655f1d5f30a1)

**Comment by shanegillio** [comment]
@kennethlinzj can you try downloading this version and then checking for updates: https://f000.backblazeb2.com/file/altstore/altserver/1_6.zip

You should see version 1.6.2 as an available update, and then it shouldn't let you download 1.7

**Comment by kennethlinzj** [comment]
Thanks, I didn’t need to do that as my app itself found the 1.16.2 update. Thank you for the help.
