### ISSUE TITLE
Failed to Log In -29004

### ISSUE THREAD

**Issue by babaruh** [altstoreio/AltStore#1333]
the problem is related to altstore on linux. https://github.com/NyaMisty/AltServer-Linux hasn't had any new releases for almost 2 years now (so it's unlikely that this is related to it), everything was working fine until a certain point (for me 1_6_3 worked), but recently I got an error when logging into the altstore "Failed to Log In. This action could not be completed due to possible environment mismatch. (-29004)"
if you try to reinstall altstore or anything else, you will get an error on linux
```
filesystem error: directory iterator cannot open directory: No such file or directory [C:\ProgramData\Apple Computer\iTunes\adi]
Press any key to continue...

Exception: filesystem error: directory iterator cannot open directory: No such file or directory [C:\ProgramData\Apple Computer\iTunes\adi]
 0# 0x08234CD7
 1# 0x08657482
```

if you use the local anisette-server(like https://hub.docker.com/r/nyamisty/alt_anisette_server), you can install any app, but the same error with the altstore login remains

I tried installing different versions of altstore (1.6.3, 1.7), but the same error.

the actual question is what is this error related to?

**Comment by shanegillio** [comment]
Hi! We aren't planning any further development on AltServer Linux, so I would recommend posting this issue to NyaMisty's github instead - sorry!
