### ISSUE TITLE
Altstore and other apps are not opening

### ISSUE THREAD

**Issue by sfksuperman** [altstoreio/AltStore#1341]
I have 5 days remaining to refresh the apps inside Altstore but all of sudden no apps are opening, even the altstore app itself. When I click on it, it just pops up and closes.
I checked in my settings and all apps are now in NOT VERIFIED state.
I tried to VERIFY APPS but that's also not working.

Could you please check why this is happening and how to fix it?

![be image](https://github.com/altstoreio/AltStore/assets/34414624/f81702c0-a0a0-40b9-9932-5b039283c562)

**Comment by sfksuperman** [comment]
I faced this issue now for the first time on iOS 17.1.1. All I need to do is connect my phone to pc again, reinstalled the Altstore again and it opens up, refresh all 2 installed apps and now they are also working.
Weird to see it stopped working without anything I did though!

![image](https://github.com/altstoreio/AltStore/assets/34414624/709b7e24-61ee-4c87-889a-b9b4853f74da)

![image](https://github.com/altstoreio/AltStore/assets/34414624/3033e158-84cb-4811-aa79-2b949ffeee74)

![image](https://github.com/altstoreio/AltStore/assets/34414624/735bdc3e-3aab-4a90-bf19-28061947c5d6)

**Comment by shanegillio** [comment]
This would likely have been a network issue where the apps could not be verified the last time you refreshed. There isn't anything we can do on our end to make sure the app is verified, and you can only make sure when you install that this does happen as it should.
