### ISSUE TITLE
JIT could not be enabled for Altstore.

### ISSUE THREAD

**Issue by sfksuperman** [altstoreio/AltStore#1342]
**iOS 17.1.1**
Why it's not working? And, it's not even mentioned in the FAQ anywhere.

<img width="454" alt="image" src="https://github.com/altstoreio/AltStore/assets/34414624/24a6bb36-dec7-4949-add8-8550b9f9afdf">

**Comment by sfksuperman** [comment]
Found this link https://faq.altstore.io/how-to-use-altstore/altjit, but it still says the same issue in the phone's altstore.

**Comment by sfksuperman** [comment]
Oh, sad to know it's not supported for Windows yet! Damn!

**Comment by aellul27** [comment]
Would it be possible to generate the developer disk on MacOS then use it on Windows later?

**Comment by sfksuperman** [comment]
Atleast give hint when it can be fixed?
