### ISSUE TITLE
how to enable jit for iPhone(iOS 17) on altstore 1.6.2?

### ISSUE THREAD

**Issue by whaleboss** [altstoreio/AltStore#1343]
my MacOs version is 10.15.7 and install altstore 1.6.2
https://faq.altstore.io/getting-started/how-to-install-altstore-macos
my iPhone version is iOS 17.1
I enter the conmands from the instruction:
https://faq.altstore.io/how-to-use-altstore/altjit
When i enable jit, the error code is "The URL to download the Developer disk image could not be determined" 
More details is AltServer.DeveloperDiskError 0
how to solve the problem?
thanks a lot

**Comment by shanegillio** [comment]
Have you licked "check for updates" on Altserver? These would appear if you are running an older version - should be on 1.7

**Comment by whaleboss** [comment]
> Have you licked "check for updates" on Altserver? These would appear if you are running an older version - should be on 1.7

https://faq.altstore.io/getting-started/how-to-install-altstore-macos
the article says "If you are on macOS 10.14 or 10.15, download AltServer 1.6.2"
The latest version of my MacBook is 10.15.7

**Comment by Devyy21** [comment]
> However, I'm fighting other errors right now (device not found errors). So I can't say this a "for sure" fix.

Any success connecting your iDevice to your VM? AltStore never recognizes it the way i tried :(

**Comment by hscumbie** [comment]
I wish I could say I got a solution. I think it has something to do with Parallels assigning it to the USB 2.0 interface instead of USB 3.0/3.1 interface.

**Comment by Devyy21** [comment]
> I wish I could say I got a solution. 

Have you tried installing macOS 14 (Sonoma) on a VM and enabling JIT via Xcode debugger? I heard that that works, but I can't even get as far as installing Sonoma on Virtualbox as it bootloops after Installation, despite trying fixes and following numerous tutorials that promise it to work... also im not using AMD (apparently doesnt work on AMD chips) 

Im now trying again by creating my own macOS 14 ISO file in my macOS 12 VM... hope it works, i'll Update later if it worked or Not

**Comment by hscumbie** [comment]
That's a really good suggestion. I tried installing Xcode onto my VM. Unfortunately, it still won't see my device. I've opened a ticket with Parallels since I believe its a Parallels virtualization issue. I'll report back what I find.


In another note, what is your host system? MacOS? Windows?

**Comment by Devyy21** [comment]
> In another note, what is your host system? MacOS? Windows?

Windows 11, otherwise I wouldnt really need to use a VM (its been a painful journey so far). I cant get the Sonoma ISO I created to my host system either, as file sharing doesnt really work without guest extensions (which dont work on macOS 12)... Ahhh man, I really regret updating from iOS 16.5 to 17.1.2, I didnt know they changed how JIT was handled, and i never needed it before, but of course I do now... Ill keep trying to get stuff to work on a VM tho.

**Comment by hscumbie** [comment]
Does the vm have access to a network adapter? Might could do SCP.

**Comment by Devyy21** [comment]
Just tried directly installing Sonoma / updating from Monterey to Sonoma on my VM... Completely crashed everything now. I've seen others using VMware instead of Virtualbox to successfully debug via xcode, so I'll try installing Sonoma on VMware now and see how it goes

**Comment by Devyy21** [comment]
Also still can't get over the fact that iOS is this limited... u can spend so much time trying to do stuff that u can do with a few clicks on android... gotta love and hate apple ig

**Comment by Devyy21** [comment]
Finally, after all this work, VMware does support USB 3.1 and AltStore recognizes my iDevice! 
Now I'll try following the steps to (hopefully) successfully enable JIT!

**Comment by kadeschs** [comment]
> Now I'll try following the steps to (hopefully) successfully enable JIT!

well, did it work? All these kinds of threads keep going dead with no follow-ups or solutions.

**Comment by Devyy21** [comment]
> > Now I'll try following the steps to (hopefully) successfully enable JIT!
> 
> well, did it work? 

Yeah it worked, however it does take about 1 min. which means the app to enable JIT on has to stay in foreground during that minute, which also means that apps which require instant JIT access wont work and will get shutdown by the iOS system before JIT can be enabled.

**Comment by hscumbie** [comment]
I got mine working using VMWare and a Sonoma VM on my MacBook Air.

**Comment by kadeschs** [comment]
Where did you get your Sonoma image from?

**Comment by Devyy21** [comment]
> Where did you get your Sonoma image from?

as for me, all available online did not work, so I downloaded a macOS Monterey image, installed macOS on VMware, loaded the Updater for MacOS Sonoma from the AppStore and followed a YouTube tutorial to turn it into an .iso file...

**Comment by hscumbie** [comment]
If you own a Mac, you can make one yourself as well.

**Comment by kadeschs** [comment]
> EDIT: Now that I think about it, this one should actually work: https://www.mediafire.com/file/vku90kjifs1fmu0/macOS+Sonoma+ISO+by+techrechard.com.iso/file

Will give it a shot.  Thanks!

**Comment by Devyy21** [comment]
> If you own a Mac, you can make one yourself as well.

Why use a VM in the first place if u have a mac already? Just directly update to sonoma and use AltStore for Mac 🤔

**Comment by Devyy21** [comment]
> > EDIT: Now that I think about it, this one should actually work: https://www.mediafire.com/file/vku90kjifs1fmu0/macOS+Sonoma+ISO+by+techrechard.com.iso/file
> 
> Will give it a shot. Thanks!

No problem, let me know if it works or not :)

**Comment by hscumbie** [comment]
> > If you own a Mac, you can make one yourself as well.
> 
> 
> 
> Why use a VM in the first place if u have a mac already? Just directly update to sonoma and use AltStore / AltJIT for Mac 🤔

2017 MacBook Air. Stuck on Monterey 😂. Only Ventura and newer support Xcode 15 which supports iOS 17. You have to have Xcode 15 support to use the developerdiskimage needed by `pymobiledevice3` when using AltJIT

**Comment by kadeschs** [comment]
Same deal here too. On Mac Mini 2011 and can’t upgrade OS any longer. Sounds as if people need a recent Mac in order to get JIT working on iOS 17.

**Comment by hscumbie** [comment]
Yeah. VMWare fusion worked great for me. I recommend making a Ventura VM cause it's less buggy than Sonoma.

**Comment by Devyy21** [comment]
> Same deal here too. On Mac Mini 2011 and can’t upgrade OS any longer. Sounds as if people need a recent Mac in order to get JIT working on iOS 17.

Yeah, either that or use a VirtualMachine like VMware which worked for me without a problem (dont try Virtualbox, it's a pain in the a** and won't even work in the end, trust me)

**Comment by kadeschs** [comment]
Ended up getting mine working through VMWare as well. Doesn’t surprise me about Vb. I’ve used VMWare for many years, and it’s always been the best out there.
