### ISSUE TITLE
AltStore Linux support?

### ISSUE THREAD

**Issue by MrGamerDoesGames** [altstoreio/AltStore#1346]
Come on, if this would be possible it would be great to see. The idea of AltStore and Linux users go together like bread and butter, so why not allow us to not have to dual boot windows or keep that old Mac around? You could even make it a flatpak/snap to not have to worry about repackaging for different distributions.

**Comment by shanegillio** [comment]
See Issue: https://github.com/altstoreio/AltStore/issues/712

**Comment by sequencer** [comment]
Is there any upstate on the linux support?
