### ISSUE TITLE
Failed to enable AltJIT on MacOS due to missing binary "mounter"

### ISSUE THREAD

**Issue by HouzuoGuo** [altstoreio/AltStore#1347]
The macos kernel version is:

```
Darwin howardguo 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 x86_64
```

When enabling jit for UTM, the following error appears:

```
Error Description
The process 'altjit' failed with code 1. The process 'python3' failed with code 2. Error: No such command 'mounter'.

Failure Reason
The process 'altjit' failed with code 1. The process 'python3' failed with code 2. Error: No such command 'mounter'.

Title
JIT could not be enabled for UTM.

Source Line
96

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
Mounting personalized developer disk...
❌ Unable to mount personalized Developer Disk.
The process 'python3' failed with code 2. Error: No such command 'mounter'.
```

**Comment by HouzuoGuo** [comment]
Thank you, I’m probably going to revisit altjit in the future, for now I’ll check something else out.

**Comment by Jedidude** [comment]
I have this exact same issue.
Macbook Pro 14 M1 Pro MacOS 14.4.1
iPhone 11 Pro iOS 17.4.1

**Comment by mv-stns** [comment]
> Thank you, I’m probably going to revisit altjit in the future, for now I’ll check something else out.

Still not working, mounter missing...
```
Error Description
The process 'altjit' failed with code 1. The process 'python3' failed with code 2. Error: No such command 'mounter'.

Failure Reason
The process 'altjit' failed with code 1. The process 'python3' failed with code 2. Error: No such command 'mounter'.

Title
JIT could not be enabled for DolphiniOS.

Source Line
96

executableURL
file:///private/var/folders/gn/qgfmldqx6jz0kydhct25sw1w0000gn/T/AppTranslocation/EF944FFC-7378-4B71-A417-7F88B8573845/d/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
Mounting personalized developer disk...
❌ Unable to mount personalized Developer Disk.
The process 'python3' failed with code 2. Error: No such command 'mounter'.

**Comment by jooxy884** [comment]
same problem, help

**Comment by dmuiX** [comment]
`python3 -m pip install -U --break-system-packages pymobiledevice3`

using this helped me to come by the error.

Got another one now :D. But I'm getting closer.
Something with Developer Mode not Activated.
Pretty easy to come by that error: https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

still it lowers the security of my device so I will not use it

**Comment by cddude** [comment]
I have all of these things activated and I get the same error as OP.  Develope mode is on, i'm even hardwired to the Mac, pymobiledevice3 is installed etc.  Can't get JIT to enable.
