### ISSUE TITLE
Unable to launch altstore beta

### ISSUE THREAD

**Issue by PerroniClaudio** [altstoreio/AltStore#1366]
While installing the beta version it's giving me the following error.

![WhatsApp Image 2023-12-30 at 12 27 02](https://github.com/altstoreio/AltStore/assets/70200257/ad89fd5d-e04c-4ecc-9725-a0b68bb602c3)

iPhone 15 - iOS 17.1.2

**Comment by shanegillio** [comment]
THis happens if you launch the public version again. Make sure to follow the instructions on the FAQ for the beta and to delete the public version after installing the beta.
