### ISSUE TITLE
Important! I can't enable JIT on iphone. please help!

### ISSUE THREAD

**Issue by yugioh2king** [altstoreio/AltStore#1369]
I need some help I cannot enable jit on my iphone it keeps saying "JIT could not be enabled for Altstore. The Url to download the Develop disk image could not be determined.

AltServer. DeveloperDiskError 0

Error Description
The URL to download the Developer disk image could not be determined.

Failure Reason
The URL to download the Developer disk image could not be determined.

Title
JIT could not be enabled for AltStore.

Source File
AltServer/DeveloperDiskManager.swift

Source Line
150

My Device is Iphone xs max ios ver 17.2.1
macbook mac os is big sur ver 11.7.10

I can't update to the latest macos, because mine is an early 2014. Is the developer going to have support on older mac os if they find a fix?

**Comment by realgamebreaker** [comment]
Same here.
![image](https://github.com/altstoreio/AltStore/assets/98226581/30f04569-0c85-4faa-8ca6-9a27cd2c0f6e)

**Comment by l3gacyb3ta** [comment]
You can't do JIT on 17.2 yet it seems, and JIT for 17 isn't working on windows yet

**Comment by yugioh2king** [comment]
> You can't do JIT on 17.2 yet it seems, and JIT for 17 isn't working on windows yet

Okay do you know if older versions of mac os will work if the developer find a way to solve this. Mine is a macbook with mac os is big sur ver 11.7.10. (Early 2014) And my iphone xs max is on ios ver. 17.2.1

**Comment by nixybuilder** [comment]
im on 17.4 and the altstore pal is useless you cant install anything idk its just all useless

**Comment by Bufka2011** [comment]
What about iOS 12.5.7?
