### ISSUE TITLE
Why is Windows not getting AltStore updates?

### ISSUE THREAD

**Issue by lunarnaut3** [altstoreio/AltStore#1370]
I want to be able to enable Jit on my apps on iOS 17 but I can't because I'm on v1.6.1 which is the most recent version available for windows. v1.7 fixes the issue me, and many other people have, but it is only available for MacOS.

**Comment by shanegillio** [comment]
The current process for JIT on iOS 17 requires workarounds only available on Mac at the moment. Once a solution for Windows can be found, then further progress can be made for JIT on Windows with iOS 17
