### ISSUE TITLE
Error enabling JIT

### ISSUE THREAD

**Issue by SandStormDEVOfficial** [altstoreio/AltStore#1409]
I've installed everything need to run jit on MACOS, but I'm still getting the standard error about loading developer "blablabla" 
MACOS: monterrey
Ios:17.3
![image](https://github.com/altstoreio/AltStore/assets/141961472/1f6de7f5-f032-4404-9f75-9e196ef801a7)

**Comment by hscumbie** [comment]
See [this](https://github.com/altstoreio/AltStore/issues/1349) issue I posted with the same issue. It is related to Monterey no longer being supported to use Developer Tools for iOS 17. A workaround is to use VMWare Fusion and create a macOS Ventura VM and do everything in that environment.
