### ISSUE TITLE
Installation failed: Unknown services responce error. (-1)

### ISSUE THREAD

**Issue by Pupcheg** [altstoreio/AltStore#231]
**Describe the bug**
AltStore on IPad is not installed/

**To Reproduce**
1. Go to 'Install AltStore'
2. Click on 'IPad'
3. Entering my AppleID and password
4. Waiting ~3 seconds
5. See error

**Expected behavior**
Installed AltStore

**Screenshots**
![image](https://user-images.githubusercontent.com/66114027/83240119-92a03180-a1a1-11ea-8532-ce9a28975664.png)

**Desktop**
 - OS: Windows
 - Version: 10

**iPhone (please complete the following information):**
 - Device: IPad mini 4 (WiFi)
 - iOS: 13.4

**Comment by k2navas** [comment]
same issuse any other way try not working

**Comment by joyater** [comment]
same here

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?
