### ISSUE TITLE
Could not find provisioning profile

### ISSUE THREAD

**Issue by shecravesaldo** [altstoreio/AltStore#554]
This may seem like a repeat of a different issue posted before, but i've experienced the same thing with a different ios and os version. When i try to install altstore, I get a message on my computer saying "Could not find provisioning profile" and when I try to open altstore on my phone, it says "Unable to Launch Altstore" with "The file 'Apps' couldn't be saved in the folder "Application Support" under it.

**To Reproduce**

1. Delete altstore
2. Install altstore and enter Apple ID
3. Error message "Could not find provisioning profile" on computer
4. Trust developer profile on phone
5. Open Altstore on iphone
6. "The file 'Apps' couldn't be saved in the folder "Application Support" pops up

- OS: Windows
- Version: 10
-Device: iphone
-IOS: 13.5

**Additional context**
Im using altserver 1.3.1 because on later versions, I would get the error message of "iswow64process2 could not be located" and when I first jailbroke my phone, version 1.3.1 worked fine. My phone has already been jailbroken and cydia is still in my homescreen.

**Comment by Dgruyere** [comment]
Got the same error on Windows 10 iPhone SE, iOS 13.6.1

**Comment by huyle0406** [comment]
If anyone get error “The provisioning profile is invalid” after updating to ios 14 and tried reinstall everything, try this method. 
Use filza and delete all the files in /var/MobileDevice/ProvisioningProfiles

Hope this help you.

**Comment by shecravesaldo** [comment]
I’ve stayed on 13.5. Anyway to fix it? Or be able to move “apps” to “application support”

**Comment by mrk2099** [comment]
> If anyone get error “The provisioning profile is invalid” after updating to ios 14 and tried reinstall everything, try this method.
> Use filza and delete all the files in /var/MobileDevice/ProvisioningProfiles
> 
> Hope this help you.

I know it was last year when this was mentioned but I had just been going through the same issue right now with Altstore on windows, I saw a bunch of provisioning files on my iPhone X, iOS 14.3, I just wanted to confirm if I should delete on those provisioning profiles that had appeared in filza through the file path. Thanks

**Comment by mrk2099** [comment]
Edit: followed the steps as the previous message had stated with the file path to remove the provisioning profiles through filza and still have the same issue on my XS max

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by apivovarov** [comment]
(3017) There is no provisioning profile with the requested identifier on this team.
AltStore.AppleDeveloperError
If you are seeing this error, it's likely due to a recent server-side change made by Apple. Please see the following announcement with more info: https://twitter.com/altstoreio/status/1637953768728801282?s=20
