### ISSUE TITLE
No response after entering apple id

### ISSUE THREAD

**Issue by huangdihd** [altstoreio/AltStore#685]

**Comment by huangdihd** [comment]
Does anyone answer this question?

**Comment by CoreISP** [comment]
> Does anyone answer this question?

I don’t see a question?

**Comment by cadegorawrz** [comment]
Having the same issue. Whenever I try to sign in with my Apple ID on the AltStore app it just infinitely loads. Running IOS 14.5 on an 2018 11" iPad Pro.
