### ISSUE TITLE
error = 1

### ISSUE THREAD

**Issue by ExtincTay** [altstoreio/AltStore#760]
i get an error message everytime i try to use alt store 
![image](https://user-images.githubusercontent.com/52536506/118288724-93be9180-b4cc-11eb-97e6-aab1aee46344.png)

(EDIT) so i tried on another device and that worked. does altstore not work on the iphone se (old  version) ?

**Comment by goopy13** [comment]
Same issue, iPhone SE 1st gen 14.6.

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by ExtincTay** [comment]
i didnt get any notifications here (thanks github) i resolved the issue i just dont remember how as it was a while ago and i dont use alt store anymore
